[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "24"

# allow internal routing history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
