version: 2

jobs:
  lint_and_test:
    docker:
      - image: node:16.18.1-alpine
    steps:
      - checkout
      - run:
          name: client install
          command: cd client && npm ci --ignore-scripts && cd -
      - run:
          name: server install
          command: cd server && npm ci --ignore-scripts && cd -
      - run:
          name: client lint
          command: cd client && npm run lint && cd -
      - run:
          name: server lint
          command: cd server && npm run lint && cd -
      - run:
          name: client test
          command: cd client && npm run test && cd -
      - run:
          name: server test
          command: cd server && npm run test && cd -
  e2e:
    docker:
      - image: cypress/base:16.18.1
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: client install
          command: cd client && npm ci --ignore-scripts && cd -
      - run:
          name: server install
          command: cd server && npm ci --ignore-scripts && cd -
      - run:
          name: e2e install
          command: cd e2e && npm ci && cd -
      - run:
          name: e2e test
          command: cd e2e && npm run test && cd -
      - store_artifacts:
          path: e2e/src/screenshots

workflows:
  version: 2
  dev-worflow:
    jobs:
      - lint_and_test
      - e2e
