dockerConfig: &dockerConfig
  docker:
    - image: circleci/node:10

version: 2

jobs:
  build:
    <<: *dockerConfig
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: build
          command: |
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build

  lint:
    <<: *dockerConfig
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: |
            yarn lint

  test:
    <<: *dockerConfig
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: test
          command: |
            yarn test

workflows:
  version: 2
  quality:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
