version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.24.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install
          command: |
            docker-compose -f docker-compose.yaml -f docker-compose.local.yaml up -d
      - run:
          name: server lint
          command: |
            docker-compose exec server npm run lint
      - run:
          name: server test
          command: |
            docker-compose exec server npm run test
      - run:
          name: client lint
          command: |
            docker-compose exec client npm run lint
      - run:
          name: client test
          command: |
            docker-compose exec client npm run test
