version: 2

aliases:
  - &dockerImage
    docker:
      - image: node:12.7.0-alpine
  # fixes https://discuss.circleci.com/t/requesterror-x509-certificate-signed-by-unknown-authority-while-uploading-workspace/27908/3
  - &addCertificates
    run: apk add --no-cache ca-certificates

jobs:
  install:
    <<: *dockerImage
    steps:
      - *addCertificates
      - checkout
      - run:
          name: client install
          command: cd client && npm ci && cd -
      - run:
          name: server install
          command: cd server && npm ci && cd -
      - persist_to_workspace:
          root: .
          paths: '*'
  lint:
    <<: *dockerImage
    steps:
      - *addCertificates
      - attach_workspace:
          at: .
      - run:
          name: client lint
          command: cd client && npm run lint && cd -
      - run:
          name: server lint
          command: cd server && npm run lint && cd -
      - run:
          name: client build
          command: cd client && npm run build && cd -
  test:
    <<: *dockerImage
    steps:
      - *addCertificates
      - attach_workspace:
          at: .
      - run:
          name: client test
          command: cd client && npm run test && cd -
      - run:
          name: server test
          command: cd server && npm run test && cd -

  e2e:
    <<: *dockerImage
    steps:
      - *addCertificates
      - attach_workspace:
          at: .
      - run:
          name: e2e test
          command: cd client && npm run e2e:ci && cd -

workflows:
  version: 2
  dev-worflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - e2e:
          requires:
            - install
