dockerConfig: &dockerConfig
  docker:
    - image: circleci/node:11

version: 2

jobs:
  build:
    <<: *dockerConfig
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: yarn lint
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - build
